name = "workers-airtable-form"
type = "javascript"

account_id = "d1e8ec1154af6d85efd5d0608b5ef2c8"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "shrOBkdxGdRdvrnnm"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "https://workers-airtable-form.hrynkoiryna.workers.dev"
